/// Base class for unconverted or custom client-side errors that can be generated by the app
sealed class CommonError implements Exception {
  CommonError();
}

class LocalCustomError extends CommonError {
  final String error;

  LocalCustomError(this.error);

  @override
  String toString() => error;
}

class NetworkError extends CommonError {
  final String error;

  NetworkError(this.error);

  @override
  String toString() => error;
}

class ServerError extends CommonError {
  final String error;

  ServerError(this.error);

  @override
  String toString() => error;
}

class UnknownError extends CommonError {
  UnknownError();
}
