import 'package:aichat/src/utils/extensions/build_context_extensions.dart';
import 'package:flutter/material.dart';

abstract class _ExceptionWithLocalizationMessage implements Exception {
  String toLocMsg(BuildContext context);
}

/// Base class for default all client-side errors that can be generated by the app
sealed class StandardException implements _ExceptionWithLocalizationMessage {
  StandardException();
}

class UnsupportedPlatform extends StandardException {
  @override
  String toLocMsg(BuildContext context) => context.l10n.unsupportedPlatform;
}

class NoInternetException extends StandardException {
  @override
  String toLocMsg(BuildContext context) => context.l10n.noInternetConnection;
}

class ServerException extends StandardException {
  @override
  String toLocMsg(BuildContext context) => context.l10n.serverError;
}
