import 'package:aichat/src/utils/extensions/build_context_extensions.dart';
import 'package:flutter/material.dart';

abstract class _ExceptionWithLocalizationMessage implements Exception {
  String toLocMsg(BuildContext context);
}

/// Base class for all all client-side errors that can be generated by the app
sealed class LocalException implements _ExceptionWithLocalizationMessage {
  final String code;
  LocalException(this.code);
}

/// Auth
class EmailAlreadyInUseException extends LocalException {
  EmailAlreadyInUseException() : super('email-already-in-use');

  @override
  String toLocMsg(BuildContext context) => context.l10n.emailAlreadyInUse;
}

class WeakPasswordException extends LocalException {
  WeakPasswordException() : super('weak-password');

  @override
  String toLocMsg(BuildContext context) => context.l10n.weakPassword;
}

class WrongPasswordException extends LocalException {
  WrongPasswordException() : super('wrong-password');

  @override
  String toLocMsg(BuildContext context) => context.l10n.wrongPassword;
}

class UserNotFoundException extends LocalException {
  UserNotFoundException() : super('user-not-found');

  @override
  String toLocMsg(BuildContext context) => context.l10n.userNotFound;
}

/// Set Image Profile
class MaxSizeImagePickException extends LocalException {
  MaxSizeImagePickException() : super('max-size-image-pick');

  @override
  String toLocMsg(BuildContext context) => context.l10n.imageSizeTooLarge;
}
