include: package:lint/strict.yaml

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.config.dart'
    - '**/firebase_options**.dart'
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    sort_unnamed_constructors_first: false
    use_super_parameters: true
    sort_pub_dependencies: false
    require_trailing_commas: true

formatter:
  page_width: 120
  trailing_commas: preserve
