name: aichat
description: "A pet project with riverpod arch + firebase auth and firestore"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2

  # State Management and DI
  flutter_riverpod: 3.0.0-dev.17
  riverpod_annotation: 3.0.0-dev.17

  # Navigation
  go_router: ^10.1.2

  # Firebase
  firebase_core: 3.8.1
  firebase_auth: 5.3.4
  cloud_firestore: 5.5.1
  firebase_storage: 12.3.6
  firebase_crashlytics: 4.2.0
  firebase_app_check: 0.3.1+7

  # Auth
  google_sign_in: 6.1.0
  sign_in_with_apple: 6.1.1

  # UI
  flutter_screenutil: ^5.8.4
  flutter_svg: 2.0.16

  # AI
  chat_gpt_sdk: 3.1.5

  # Network
  http: ^1.2.2
  connectivity_plus: 6.1.3

  # Purchase
  purchases_flutter: 9.2.0

  # Security
  envied: 1.1.1

  # Other
  rxdart: 0.28.0
  equatable: 2.0.7
  freezed_annotation: 3.1.0
  package_info_plus: 8.3.1
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.4.6
  riverpod_generator: 3.0.0-dev.17
  riverpod_lint: 3.0.0-dev.17
  envied_generator: ^1.1.1
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: 0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: 3.2.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  lint: ^2.1.2
  mocktail: 1.0.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/ic_launcher/
    - assets/icons/
    - assets/images/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 800
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700


flutter_gen:
  output: lib/generated/
  line_length: 120
  # integrations:
  #   flutter_svg: true

# todo add flutter_native_splash
# flutter pub run flutter_native_splash:create
# flutter pub run flutter_native_splash:remove
# flutter_native_splash:
#   color: "#344E74"
#   android: true
#   ios: true
#   image: assets/logo/splash_logo.png
#   fullscreen: true
#   android_12:
#     image: assets/logo/splash_logo.png
#     icon_background_color: "#344E74"
